name: 'Install Swift'
description: 'Install the given Swift version.'

inputs:
  version:
    description: 'The Swift version to install.'
    required: true

runs:
  using: "composite"
  steps:
  - name: Determine Ubuntu Version
    run: |
      UBUNTU_VERSION=$(lsb_release -rs)

      echo "UBUNTU_VERSION=$UBUNTU_VERSION" >> $GITHUB_ENV
    shell: bash

  - name: Cache Swift Toolchain
    id: swift-toolchain-cache
    uses: actions/cache@v2
    with:
      path: /usr/share/swift-toolchain
      key: ubuntu-${{ env.UBUNTU_VERSION }}-${{ inputs.version }}

  - name: Install Swift Toolchain
    run: SWIFT_VERSION=${{ inputs.version }} $GITHUB_ACTION_PATH/install-swift.sh
    shell: bash

  - name: Print Swift Version
    run: swift --version
    shell: bash

branding:
  icon: 'briefcase'
  color: 'orange'
