name: 'Install Swift'
description: 'Install the given Swift version.'

inputs:
  version:
    description: 'The Swift version to install.'
    required: true

runs:
  using: "composite"
  steps:
  - name: Determine Cache Key
    run: |
      # ubuntu-20.04-5.5
      # macos-12.2-5.5

      SWIFT_VERSION=${{ inputs.version }}

      if [[ $SWIFT_VERSION == swift-DEVELOPMENT-SNAPSHOT* ]]; then
          RELEASE_NAME=$SWIFT_VERSION
      else
          RELEASE_NAME=swift-$SWIFT_VERSION-RELEASE
      fi

      if [ $RUNNER_OS == Linux ]; then
        PLATFORM=ubuntu-$(lsb_release -rs)
        TOOLCHAIN_PATH=/opt/swift-toolchains/$RELEASE_NAME
      elif [ $RUNNER_OS == macOS ]; then
        PLATFORM=macos-$(sw_vers -productVersion)
        TOOLCHAIN_PATH=${HOME}/Library/Developer/Toolchains/$RELEASE_NAME.xctoolchain
      fi

      echo "TOOLCHAIN_PATH=$TOOLCHAIN_PATH" >> $GITHUB_ENV
      echo "CACHE_KEY=$PLATFORM-$SWIFT_VERSION" >> $GITHUB_ENV
    shell: bash

  - name: Cache Swift Toolchain
    id: swift-toolchain-cache
    uses: actions/cache@v2
    with:
      path: ${{ env.TOOLCHAIN_PATH }}
      key: ${{ env.CACHE_KEY }}

  - name: Install Swift Toolchain
    run: SWIFT_VERSION=${{ inputs.version }} $GITHUB_ACTION_PATH/install-swift.sh
    shell: bash

  - name: Print Swift Version
    run: swift --version
    shell: bash

branding:
  icon: 'briefcase'
  color: 'orange'
