name: 'Install Swift'
description: 'Install the given Swift version.'

inputs:
  version:
    description: 'The Swift version to install.'
    required: true

runs:
  using: "composite"
  steps:
  - name: Determine Cache Key
    run: |
      # ubuntu-20.04-5.5
      # macos-12.2-5.5

      if [ $RUNNER_OS == Linux ]; then
        PLATFORM=ubuntu-$(lsb_release -rs)
      elif [ $RUNNER_OS == macOS ]; then
        PLATFORM=macos-$(sw_vers -productVersion)
      fi

      echo "CACHE_KEY=$PLATFORM-${{ inputs.version }}" >> $GITHUB_ENV
    shell: bash

  # - name: Cache Swift Toolchain
  #   id: swift-toolchain-cache
  #   uses: actions/cache@v2
  #   with:
  #     path: /opt/swift-toolchains/${{ inputs.version }}.xctoolchain
  #     key: ${{ env.CACHE_KEY }}

  - name: Install Swift Toolchain
    run: SWIFT_VERSION=${{ inputs.version }} $GITHUB_ACTION_PATH/install-swift.sh
    shell: bash

  - name: Print Swift Version
    run: swift --version
    shell: bash

branding:
  icon: 'briefcase'
  color: 'orange'
